// VC4C reconstruction fidelity fixtures
// (`conformance/vector-cortex/v2/reconstruction/`).
//
// Owner VC4C (ClosureResult / ReconstructionV1 / ReconstructionValidation). Each
// fixture declares a closure / assembly / validation condition the acceptance
// test executes against the REAL reconstruct module (src/vector-cortex/
// reconstruct/{closure,assemble,validate}.js), no mocks. `input.scenario` names
// the condition; `expected.ok` pins the successful behavior or the exact failure
// `code` (REC_SOURCE_UNAVAILABLE / REC_ANCHOR_MISSING / REC_TOOL_PAIR_SPLIT /
// REC_DIGEST_MISMATCH / REC_CONTRADICTION_UNRESOLVED / REC_SPAN_OVERLAP).
//
// CLO-001..030 pin closure behavior (transitive dependency closure, tool-pair
// atomicity, anchor floor, contradiction resolution, cycle termination);
// REC-001..030 pin assembly + validation (source-order layout, protected exact
// bytes, missing-shard rejection, split-pair rejection, digest mismatch,
// unresolved contradiction). The three NAMED rows (CLO-TRANSITIVE-001 /
// CLO-CONTRA-002 / REC-ORDER-003) pin the sprint's headline assertions.

import { producer } from "./common.mjs";

const RECONSTRUCTION_SCHEMA = "schemas/reconstruction-fixture.schema.json";

function reconstructionFixture(id, assertion, input, expected) {
  return { id, schema: RECONSTRUCTION_SCHEMA, producer, assertion, kind: "reconstruction", input, expected };
}

export const fixtures = [
  // ── Closure: transitive dependency closure (CLO-001..010) ──────────────────
  reconstructionFixture("CLO-001", "selecting a closes b and c transitively when b depends on c",
    { scenario: "closure-transitive", graph: "chain", seeds: ["a"] },
    { ok: true, selected: ["a", "b", "c"], closureReachedFixedPoint: true }),
  reconstructionFixture("CLO-002", "a diamond dependency merges without duplication",
    { scenario: "closure-diamond", graph: "diamond", seeds: ["top"] },
    { ok: true, selected: ["bottom", "l", "r", "top"], closureReachedFixedPoint: true }),
  reconstructionFixture("CLO-003", "a cycle terminates at the fixed point (no infinite recursion)",
    { scenario: "closure-cycle", graph: "cycle", seeds: ["a"] },
    { ok: true, selected: ["a", "b", "c"], closureReachedFixedPoint: true }),
  reconstructionFixture("CLO-004", "a self-loop edge terminates (node depends on itself)",
    { scenario: "closure-self-loop", graph: "selfloop", seeds: ["a"] },
    { ok: true, selected: ["a"], closureReachedFixedPoint: true }),
  reconstructionFixture("CLO-005", "two independent seeds close to the union of their dependencies",
    { scenario: "closure-two-seeds", graph: "parallel", seeds: ["a", "x"] },
    { ok: true, selected: ["a", "b", "x", "y"], closureReachedFixedPoint: true }),
  reconstructionFixture("CLO-006", "a dependency edge is walked backward to the prerequisite",
    { scenario: "closure-depends-backward", graph: "prereq", seeds: ["dependent"] },
    { ok: true, selected: ["dependent", "prereq"], closureReachedFixedPoint: true }),
  reconstructionFixture("CLO-007", "a node with no dependencies closes to just itself",
    { scenario: "closure-leaf", graph: "leaf", seeds: ["only"] },
    { ok: true, selected: ["only"], closureReachedFixedPoint: true }),
  reconstructionFixture("CLO-008", "the closure output is deterministically sorted by id",
    { scenario: "closure-deterministic-order", graph: "scrambled", seeds: ["m", "a", "z"] },
    { ok: true, closureReachedFixedPoint: true }),
  reconstructionFixture("CLO-009", "a requested seed absent from the graph returns CLO_UNKNOWN_SEED",
    { scenario: "closure-unknown-seed", graph: "leaf", seeds: ["missing"] },
    { ok: false, code: "CLO_UNKNOWN_SEED" }),
  reconstructionFixture("CLO-010", "an edge referencing a missing node returns CLO_MISSING_NODE",
    { scenario: "closure-missing-node", graph: "dangling-edge", seeds: ["a"] },
    { ok: false, code: "CLO_MISSING_NODE" }),

  // ── Closure: tool-pair atomicity + anchor floor (CLO-011..020) ─────────────
  reconstructionFixture("CLO-011", "selecting one end of a tool pair requires the other",
    { scenario: "closure-tool-pair", graph: "toolpair", seeds: ["toolcall"] },
    { ok: true, selected: ["toolcall", "toolresult"], closureReachedFixedPoint: true }),
  reconstructionFixture("CLO-012", "an anchor is always included even if not seeded",
    { scenario: "closure-anchor-floor", graph: "anchored", seeds: ["a"] },
    { ok: true, selected: ["a", "anchor"], closureReachedFixedPoint: true }),
  reconstructionFixture("CLO-013", "the anchor floor pulls its own dependencies",
    { scenario: "closure-anchor-deps", graph: "anchor-deps", seeds: ["a"] },
    { ok: true, selected: ["a", "anchor", "anchordep"], closureReachedFixedPoint: true }),
  reconstructionFixture("CLO-014", "a tool pair transitively closes through a shared dependency",
    { scenario: "closure-tool-pair-transitive", graph: "toolpair-transitive", seeds: ["toolcall"] },
    { ok: true, selected: ["shareddep", "toolcall", "toolresult"], closureReachedFixedPoint: true }),
  reconstructionFixture("CLO-015", "two tool pairs both close atomically from one seed",
    { scenario: "closure-two-pairs", graph: "two-pairs", seeds: ["a", "c"] },
    { ok: true, selected: ["a", "b", "c", "d"], closureReachedFixedPoint: true }),
  reconstructionFixture("CLO-016", "selecting the anchor alone closes to the floor",
    { scenario: "closure-anchor-only", graph: "anchored", seeds: ["anchor"] },
    { ok: true, selected: ["a", "anchor"], closureReachedFixedPoint: true }),
  reconstructionFixture("CLO-017", "an anchor that is also a tool-pair member stays unsplit",
    { scenario: "closure-anchor-pair", graph: "anchor-pair", seeds: ["toolcall"] },
    { ok: true, selected: ["anchor", "toolcall", "toolresult"], closureReachedFixedPoint: true }),
  reconstructionFixture("CLO-018", "a deep chain (8 hops) closes fully and terminates",
    { scenario: "closure-deep-chain", graph: "chain8", seeds: ["n0"] },
    { ok: true, closureReachedFixedPoint: true, selectedCount: 9 }),
  reconstructionFixture("CLO-019", "a tool pair that depends on a third node pulls all three",
    { scenario: "closure-pair-dep", graph: "pair-dep", seeds: ["toolcall"] },
    { ok: true, selected: ["common", "toolcall", "toolresult"], closureReachedFixedPoint: true }),
  reconstructionFixture("CLO-020", "multiple seeds with overlapping dependencies dedupe correctly",
    { scenario: "closure-overlap", graph: "overlap", seeds: ["a", "b"] },
    { ok: true, closureReachedFixedPoint: true }),

  // ── Closure: contradiction resolution (CLO-021..030) ───────────────────────
  reconstructionFixture("CLO-021", "an explicit resolution event names the loser directly",
    { scenario: "closure-resolution-explicit", graph: "contra-explicit", seeds: ["a"] },
    { ok: true, unresolved: [], removedContradictions: ["loser"], closureReachedFixedPoint: true }),
  reconstructionFixture("CLO-022", "a later exact resolution supersedes an earlier claim",
    { scenario: "closure-contra-later-exact", graph: "contra-later", seeds: ["a"] },
    { ok: true, unresolved: [], removedContradictions: ["early"], closureReachedFixedPoint: true }),
  reconstructionFixture("CLO-023", "equal timestamps are an unresolved tie",
    { scenario: "closure-contra-tie", graph: "contra-tie", seeds: ["a"] },
    { ok: false, code: "CLO_CONTRADICTION_UNRESOLVED", unresolved: ["x", "y"] }),
  reconstructionFixture("CLO-024", "two non-exact claims with no resolution are an unresolved tie",
    { scenario: "closure-contra-non-exact", graph: "contra-non-exact", seeds: ["a"] },
    { ok: false, code: "CLO_CONTRADICTION_UNRESOLVED", unresolved: ["x", "y"] }),
  reconstructionFixture("CLO-025", "an unresolved contradiction keeps both nodes in selection",
    { scenario: "closure-contra-keep-both", graph: "contra-tie", seeds: ["a"] },
    { ok: false, code: "CLO_CONTRADICTION_UNRESOLVED" }),
  reconstructionFixture("CLO-026", "a resolved contradiction's loser is excluded from the selection",
    { scenario: "closure-contra-excluded", graph: "contra-later", seeds: ["a"] },
    { ok: true, removedContradictions: ["early"], closureReachedFixedPoint: true }),
  reconstructionFixture("CLO-027", "a contradiction between an unselected pair does not block closure",
    { scenario: "closure-contra-unselected", graph: "contra-unselected", seeds: ["a"] },
    { ok: true, unresolved: [], closureReachedFixedPoint: true }),
  reconstructionFixture("CLO-028", "a semantic node never supersedes an exact one in a tie",
    { scenario: "closure-contra-semantic-never", graph: "contra-semantic", seeds: ["a"] },
    { ok: false, code: "CLO_CONTRADICTION_UNRESOLVED", unresolved: ["x", "y"] }),
  reconstructionFixture("CLO-029", "a resolved contradiction still closes its dependencies",
    { scenario: "closure-contra-deps", graph: "contra-deps", seeds: ["a"] },
    { ok: true, unresolved: [], closureReachedFixedPoint: true }),
  reconstructionFixture("CLO-030", "the mandatory token estimate is the content-only sum of selected nodes",
    { scenario: "closure-token-sum", graph: "tokened", seeds: ["a"] },
    { ok: true, mandatoryTokenEstimate: 30, closureReachedFixedPoint: true }),

  // ── Assembly + validation: source-order layout (REC-001..010) ──────────────
  reconstructionFixture("REC-001", "semantic and exact spans assemble solely by source offsets",
    { scenario: "assemble-source-order", graph: "ordered", shards: "ordered" },
    { ok: true, spanCount: 3, assemblySortedBySource: true }),
  reconstructionFixture("REC-002", "spans are sorted by (sessionId, seqStart, byteStart)",
    { scenario: "assemble-order-keys", graph: "scrambled-spans", shards: "scrambled-spans" },
    { ok: true, assemblySortedBySource: true }),
  reconstructionFixture("REC-003", "a protected exact span is carried through unchanged",
    { scenario: "assemble-protected", graph: "protected", shards: "protected" },
    { ok: true, protectedSpanCount: 1 }),
  reconstructionFixture("REC-004", "the output digest is over the concatenated bytes",
    { scenario: "assemble-digest", graph: "ordered", shards: "ordered" },
    { ok: true, digestIsConcatenation: true }),
  reconstructionFixture("REC-005", "closure order does not affect output order",
    { scenario: "assemble-ignores-closure-order", graph: "reverse", shards: "reverse" },
    { ok: true, assemblySortedBySource: true }),
  reconstructionFixture("REC-006", "an empty selection assembles to zero bytes",
    { scenario: "assemble-empty", graph: "empty", shards: "empty" },
    { ok: true, byteTotal: 0, spanCount: 0 }),
  reconstructionFixture("REC-007", "the mandatory token estimate is carried through unchanged",
    { scenario: "assemble-token-carried", graph: "tokened", shards: "tokened" },
    { ok: true, mandatoryTokenEstimate: 30 }),
  reconstructionFixture("REC-008", "adjacent spans concatenate without a gap or overlap",
    { scenario: "assemble-adjacent", graph: "adjacent", shards: "adjacent" },
    { ok: true, byteTotal: 21 }),
  reconstructionFixture("REC-009", "a single span assembles to its own bytes",
    { scenario: "assemble-single", graph: "single", shards: "single" },
    { ok: true, spanCount: 1 }),
  reconstructionFixture("REC-010", "all source tiers (exact/residual/semantic) coexist in one reconstruction",
    { scenario: "assemble-mixed-tiers", graph: "mixed", shards: "mixed" },
    { ok: true, spanCount: 3 }),

  // ── Assembly + validation: failure rejection (REC-011..030) ────────────────
  reconstructionFixture("REC-011", "erasing a dependency shard returns REC_SOURCE_UNAVAILABLE",
    { scenario: "validate-source-unavailable", graph: "ordered", shards: "ordered-missing", eraseShard: "b" },
    { ok: false, code: "REC_SOURCE_UNAVAILABLE" }),
  reconstructionFixture("REC-012", "a corrupted residual fallback with the source erased returns REC_SOURCE_UNAVAILABLE",
    { scenario: "validate-source-erased-residual-corrupt", graph: "ordered", shards: "ordered-corrupt-fallback", eraseShard: "b" },
    { ok: false, code: "REC_SOURCE_UNAVAILABLE" }),
  reconstructionFixture("REC-013", "a missing anchor rejects with REC_ANCHOR_MISSING",
    { scenario: "validate-anchor-missing", graph: "anchored", shards: "anchor-missing" },
    { ok: false, code: "REC_ANCHOR_MISSING" }),
  reconstructionFixture("REC-014", "a tool pair split across a gap rejects with REC_TOOL_PAIR_SPLIT",
    { scenario: "validate-tool-pair-split", graph: "toolpair", shards: "pair-split" },
    { ok: false, code: "REC_TOOL_PAIR_SPLIT" }),
  reconstructionFixture("REC-015", "a two-span overlap rejects with REC_SPAN_OVERLAP",
    { scenario: "validate-span-overlap", graph: "adjacent", shards: "overlap" },
    { ok: false, code: "REC_SPAN_OVERLAP" }),
  reconstructionFixture("REC-016", "a decoded shard whose bytes disagree with its digest fails validation",
    { scenario: "validate-digest-mismatch", graph: "single", shards: "digest-mismatch" },
    { ok: false, code: "REC_DIGEST_MISMATCH" }),
  reconstructionFixture("REC-017", "an unresolved contradiction prevents live output",
    { scenario: "validate-contradiction", graph: "contra-tie", shards: "contra-tie", closureOk: false },
    { ok: false, code: "REC_CONTRADICTION_UNRESOLVED" }),
  reconstructionFixture("REC-018", "a closure that failed its own resolution is rejected",
    { scenario: "validate-closure-failed", graph: "contra-tie", shards: "contra-tie", closureOk: false },
    { ok: false, code: "REC_CONTRADICTION_UNRESOLVED" }),
  reconstructionFixture("REC-019", "a valid closed set emits vector_cortex_reconstruction_validated",
    { scenario: "validate-emits-validated", graph: "ordered", shards: "ordered" },
    { ok: true, emits: "vector_cortex_reconstruction_validated" }),
  reconstructionFixture("REC-020", "a rejected closure emits vector_cortex_closure_rejected",
    { scenario: "validate-emits-rejected", graph: "contra-tie", shards: "contra-tie", closureOk: false },
    { ok: false, code: "REC_CONTRADICTION_UNRESOLVED", emits: "vector_cortex_closure_rejected" }),
  reconstructionFixture("REC-021", "the validated summary exposes only counts and digest (no content)",
    { scenario: "validate-summary-opaque", graph: "ordered", shards: "ordered" },
    { ok: true, summaryOpaque: true }),
  reconstructionFixture("REC-022", "a validated reconstruction contains every protected span",
    { scenario: "validate-protected-present", graph: "protected", shards: "protected" },
    { ok: true, protectedSpanCount: 1 }),
  reconstructionFixture("REC-023", "a greedy exact-only closure (mode B) excludes semantic nodes",
    { scenario: "validate-mode-b-exact-only", graph: "mixed", shards: "mixed", mode: "B" },
    { ok: true, semanticExcluded: true }),
  reconstructionFixture("REC-024", "mode B forced by a semantic validation failure still assembles exact spans",
    { scenario: "validate-mode-b-forced", graph: "mixed", shards: "mixed", mode: "B", forceModeB: true },
    { ok: true, semanticExcluded: true }),
  reconstructionFixture("REC-025", "mode C (legacy prompt) is continuity, not semantic completeness",
    { scenario: "validate-mode-c-continuity", graph: "mixed", shards: "mixed", mode: "C" },
    { ok: true, semanticLossStated: true }),
  reconstructionFixture("REC-026", "a valid reconstruction reports its byte total",
    { scenario: "validate-byte-total", graph: "ordered", shards: "ordered" },
    { ok: true, byteTotal: 18 }),
  reconstructionFixture("REC-027", "a valid reconstruction reports per-tier counts",
    { scenario: "validate-by-source", graph: "mixed", shards: "mixed" },
    { ok: true, bySource: { exact: 1, residual: 1, semantic: 1 } }),
  reconstructionFixture("REC-028", "an unresolved contradiction between two selected nodes blocks",
    { scenario: "validate-selected-contradiction", graph: "contra-tie", shards: "contra-tie", closureOk: false },
    { ok: false, code: "REC_CONTRADICTION_UNRESOLVED" }),
  reconstructionFixture("REC-029", "a tool pair kept contiguous passes validation",
    { scenario: "validate-pair-contiguous", graph: "toolpair", shards: "pair-contiguous" },
    { ok: true, spanCount: 2 }),
  reconstructionFixture("REC-030", "every protected span survives a transitive closure",
    { scenario: "validate-protected-transitive", graph: "anchor-deps", shards: "anchor-deps" },
    { ok: true, protectedSpanCount: 1 }),
];

export const named = [
  reconstructionFixture(
    "CLO-TRANSITIVE-001",
    "selecting a adds dependencies b then c (named)",
    { scenario: "closure-transitive", graph: "chain", seeds: ["a"] },
    { ok: true, selected: ["a", "b", "c"], closureReachedFixedPoint: true },
  ),
  reconstructionFixture(
    "CLO-CONTRA-002",
    "the later exact resolution supersedes the earlier claim (named)",
    { scenario: "closure-contra-later-exact", graph: "contra-later", seeds: ["a"] },
    { ok: true, unresolved: [], removedContradictions: ["early"], closureReachedFixedPoint: true },
  ),
  reconstructionFixture(
    "REC-ORDER-003",
    "semantic and exact spans assemble by source offsets (named)",
    { scenario: "assemble-source-order", graph: "ordered", shards: "ordered" },
    { ok: true, spanCount: 3, assemblySortedBySource: true },
  ),
];
