/** VC2C acceptance aggregator — ENC-017..020 + named fixtures against the REAL
 *  calibrate/select/fallback producers (no mocks). Sprint: encoder qualification
 *  + calibration.
 *
 *  Scopes: QualifiedEncoderV1/CalibrationV1 registration + registration order,
 *  every conformance row resolved through the real producers, calibration fit on
 *  the calibration split only (held-out labels prohibited), split assignment
 *  generated by repository+session group (no group crosses a split; selection
 *  invariant to row order), atomic eligibility across all MODEL_ASSET + per-head
 *  EVALUATION thresholds (one failed causal head demotes all of A), the clean
 *  package listing under 35 MiB (ENC-PACK-003), unique failure injection
 *  (corrupt qualification manifest after calibration but before selection ->
 *  ENC_QUALIFICATION_DIGEST_MISMATCH and choose B), forced triad A/B/C through
 *  the qualification fallback, flag-OFF parity, and the VC2C emit seam (both
 *  named events).
 */
import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import {
  ENC2C_IDS,
  ENC_QUALIFICATION_FAIL,
  type CalibrationV1,
  type EncoderHeadName,
  type EncoderHeldOutMetrics,
} from "./encoder/types.js";
import type { QualificationCandidate } from "./encoder/select.js";
import { fitCalibration, calibrationSplitDigest, type CalibrationExample } from "./encoder/calibrate.js";
import { selectQualifiedEncoder, qualificationManifestDigest } from "./encoder/select.js";
import { selectQualificationFallback } from "./encoder/fallback.js";
import { createEncoderQualificationReporter } from "./encoder/emit-vc2c.js";
import { ENCODER_TRIGRAM_WIDTH } from "./encoder/trigram.js";
import { embedLexical, ENCODER_LEXICAL_WIDTH, ENCODER_LEXICAL_LIMITATION } from "./encoder/lexical.js";
import { canonicalManifestsConverge } from "./conformance/manifest.js";
import { VC2C_ENABLED } from "../config/vector-cortex.js";

// Q03 (flag-off parity): like VC2B, do NOT pin the flags ON at module scope —
// the mandated flag-off gate must genuinely exercise the flag-independent
// producer paths (calibrate/select/fallback math, split invariants) under the
// external OFF env. Only the ON-dependent emit/triad scenarios self-pin via
// `withFlagsOn`, valid under either external env.
function withFlagsOn(fn: () => void): void {
  const keys = ["MEGACOMPACT_VC2C", "MEGACOMPACT_VC2B", "MEGACOMPACT_VC2A"] as const;
  const saved = new Map<string, string | undefined>();
  for (const k of keys) {
    saved.set(k, process.env[k]);
    process.env[k] = "1";
  }
  try {
    fn();
  } finally {
    for (const k of keys) {
      const v = saved.get(k);
      if (v === undefined) delete process.env[k];
      else process.env[k] = v;
    }
  }
}

const HERE = dirname(fileURLToPath(import.meta.url));
function repoRoot(from: string): string {
  let dir = from;
  for (let i = 0; i < 8; i++) {
    if (existsSync(joinX(dir, "conformance", "vector-cortex"))) return dir;
    const next = dirname(dir);
    if (next === dir) break;
    dir = next;
  }
  throw new Error("conformance corpus not found above " + from);
}
import { join as joinX } from "node:path";
const REPO_ROOT = repoRoot(HERE);
const V2 = joinX(REPO_ROOT, "conformance", "vector-cortex", "v2");

interface ManifestDef {
  owner: string;
  domain: string;
  fixtures: { id: string; path: string; algorithm: string; expected: string }[];
}
interface QFixture {
  id: string;
  kind: string;
  producer: string;
  input: { scenario: string; head?: string };
  expected: {
    ok: boolean;
    code?: string;
    mode?: string;
    budgetBytes?: number;
    splitDigest?: string;
  };
  assertion: string;
}
function readManifest(): ManifestDef {
  return JSON.parse(readFileSync(joinX(V2, "manifest.json"), "utf8")) as ManifestDef;
}
function fixture(id: string): QFixture {
  const m = readManifest();
  const row = m.fixtures.find((f) => f.id === id);
  assert.ok(row, `fixture ${id} registered`);
  return JSON.parse(readFileSync(joinX(V2, row.path), "utf8")) as QFixture;
}

const VC2C_NAMED = ["ENC-CAL-001", "ENC-ATOMIC-002", "ENC-PACK-003"];
const ALL_VC2C_IDS = [...ENC2C_IDS, ...VC2C_NAMED];

/** A fully satisfactory held-out metrics set (all EVALUATION thresholds pass). */
function fullMetrics(): EncoderHeldOutMetrics {
  return {
    semantic: { spearman: 0.8, recallAt10: 0.95 },
    dependency: { precision: 0.98, recall: 0.96 },
    contradiction: { precision: 0.99, recall: 0.95, ece: 0.03 },
    cacheStability: { precision: 1.0, recall: 0.95 },
    payloadRouting: { macroF1: 0.98, exactAnchorRecall: 1.0 },
    reconstruction: { votesOk: true, dependencyClosureRecall: 1.0, taskSuccessNonInferior: true },
  };
}

/** A held-out set with the causal dependency head below its precision threshold. */
function oneFailedCausalHead(): EncoderHeldOutMetrics {
  return { ...fullMetrics(), dependency: { precision: 0.9, recall: 0.96 } }; // precision < .97
}
/** A held-out set with the semantic head below its spearman threshold. */
function semanticFail(): EncoderHeldOutMetrics {
  return { ...fullMetrics(), semantic: { spearman: 0.5, recallAt10: 0.95 } };
}

/** A deterministic calibration example set grouped by repository+session. */
function calExamples(): CalibrationExample[] {
  return [
    { itemId: "a1", head: "semantic", score: 0.2, label: 0, repository: "repoA", session: "s1" },
    { itemId: "a2", head: "semantic", score: 0.9, label: 1, repository: "repoA", session: "s1" },
    { itemId: "b1", head: "dependency", score: 0.1, label: 0, repository: "repoB", session: "s2" },
    { itemId: "b2", head: "dependency", score: 0.8, label: 1, repository: "repoB", session: "s2" },
    { itemId: "c1", head: "contradiction", score: 0.3, label: 0, repository: "repoC", session: "s3" },
    { itemId: "c2", head: "contradiction", score: 0.85, label: 1, repository: "repoC", session: "s3" },
    { itemId: "d1", head: "cacheStability", score: 0.15, label: 0, repository: "repoD", session: "s4" },
    { itemId: "d2", head: "cacheStability", score: 0.95, label: 1, repository: "repoD", session: "s4" },
    { itemId: "e1", head: "payloadRouting", score: 0.4, label: 0, repository: "repoE", session: "s5" },
    { itemId: "e2", head: "payloadRouting", score: 0.7, label: 1, repository: "repoE", session: "s5" },
  ];
}

/** A fully-fit calibration over the calibration split (reusable across tests). */
function validCalibration(): CalibrationV1 {
  const fit = fitCalibration(calExamples());
  assert.equal(fit.ok, true);
  return fit.ok ? fit.calibration : (() => { throw new Error("fit failed"); })();
}

function cleanCandidate(calibration: CalibrationV1, heldOut: EncoderHeldOutMetrics): QualificationCandidate {
  return {
    modelVersion: "vc2c-test",
    asset: { maxTokens: 512, latencyP95Ms: 20, rssDeltaMib: 40 },
    onnxDigest: "a".repeat(64),
    // Real ModelManifestV1 asset-manifest digest (SHA-256 of manifest.json
    // bytes); distinct from the onnx digest so the asset/manifest/calibration
    // digests are each pinned by their own value.
    assetManifestDigest: "b".repeat(64),
    calibration,
    heldOut,
  };
}

// ---------------------------------------------------------------------------
// Suite 1 — registration + canonical corpus (owner VC2C)
// ---------------------------------------------------------------------------
describe("VC2C conformance registration", () => {
  test("manifest registers every ENC-017..020 + named fixture, owner + domain list VC2C", () => {
    const m = readManifest();
    const ids = new Set(m.fixtures.map((f) => f.id));
    for (const id of ALL_VC2C_IDS) assert.ok(ids.has(id), `missing ${id}`);
    assert.ok(m.owner.includes("VC2C"), "owner lists VC2C");
    assert.ok(m.domain.includes("encoder-qualification"), "domain lists encoder-qualification");
    for (const id of ALL_VC2C_IDS) {
      const row = m.fixtures.find((f) => f.id === id)!;
      assert.equal(row.algorithm, "encoder-qualification", `${id} algorithm`);
    }
  });
  test("the committed VC2C corpus is canonical (a single reproducible digest)", () => {
    assert.equal(canonicalManifestsConverge(V2), true, "committed corpus converges");
  });
  test("VC2C contract registration before selection logic: ENC2C_IDS is the 4 rows", () => {
    assert.deepEqual(ENC2C_IDS, ["ENC-017", "ENC-018", "ENC-019", "ENC-020"]);
  });
});

// ---------------------------------------------------------------------------
// Suite 2 — ENC-017..020 conformance rows through the real producers
// ---------------------------------------------------------------------------
describe("ENC-017..020 conformance rows", () => {
  test("ENC-017: a fully satisfactory held-out set qualifies as mode A", () => {
    const fx = fixture("ENC-017");
    assert.equal(fx.expected.ok, true);
    const verdict = selectQualifiedEncoder(cleanCandidate(validCalibration(), fullMetrics()));
    assert.equal(verdict.ok, true);
    if (verdict.ok) {
      assert.equal(verdict.mode, "A");
      assert.equal(verdict.qualified.schema, "qualified-encoder-v1");
      assert.equal(verdict.qualified.onnxDigest.length, 64);
      // assetDigest pins the REAL ModelManifestV1 asset-manifest digest (SHA-256
      // of the manifest bytes), not a calibration-derived hash — reconciled with
      // the dashboard health card's encoderAssetDigest semantics (reviewer S1/S2).
      assert.equal(verdict.qualified.assetDigest, "b".repeat(64));
      assert.equal(
        verdict.qualified.assetDigest,
        cleanCandidate(validCalibration(), fullMetrics()).assetManifestDigest,
        "assetDigest equals the candidate's ModelManifestV1 manifest digest",
      );
      // assetDigest (manifest) and calibrationDigest (split assignment) are
      // distinct non-overlapping digests.
      assert.notEqual(verdict.qualified.assetDigest, verdict.qualified.calibrationDigest);
    }
  });

  test("ENC-018: calibration fit produces a split digest and a CalibrationV1", () => {
    const fx = fixture("ENC-018");
    assert.equal(fx.expected.ok, true);
    const cal = validCalibration();
    assert.equal(cal.schema, "calibration-v1");
    assert.equal(cal.fittedOnCalibrationOnly, true);
    assert.equal(cal.calibrationSplitDigest.length, 64);
    assert.deepEqual(cal.headOrder, ["semantic", "dependency", "contradiction", "cacheStability", "payloadRouting"]);
    for (const h of cal.headOrder) assert.equal(Number.isFinite(cal.temperatures[h]), true);
  });

  test("ENC-019: one failed causal head demotes the entire A", () => {
    const fx = fixture("ENC-019");
    assert.equal(fx.expected.ok, false);
    assert.equal(fx.expected.code, ENC_QUALIFICATION_FAIL.THRESHOLD_FAILED);
    const verdict = selectQualifiedEncoder(cleanCandidate(validCalibration(), oneFailedCausalHead()));
    assert.equal(verdict.ok, false);
    if (!verdict.ok) {
      assert.equal(verdict.code, ENC_QUALIFICATION_FAIL.THRESHOLD_FAILED);
      assert.equal(verdict.failedField, "head.dependency");
    }
  });

  test("ENC-020: corrupt qualification manifest after calibration demotes A to B", () => {
    const fx = fixture("ENC-020");
    assert.equal(fx.expected.ok, false);
    assert.equal(fx.expected.code, ENC_QUALIFICATION_FAIL.DIGEST_MISMATCH);
    const cal = validCalibration();
    // Seal a manifest digest, then corrupt the calibration (present a different
    // calibration digest) -> the corrupt-qualification-manifest injection.
    const expected = qualificationManifestDigest(cal);
    const corruptCal: CalibrationV1 = { ...cal, calibrationSplitDigest: "f".repeat(64) };
    const verdict = selectQualifiedEncoder(
      { ...cleanCandidate(cal, fullMetrics()), calibration: corruptCal, expectedQualificationManifestDigest: expected },
    );
    assert.equal(verdict.ok, false);
    if (!verdict.ok) {
      assert.equal(verdict.code, ENC_QUALIFICATION_FAIL.DIGEST_MISMATCH);
      assert.equal(verdict.mode, "B", "digest mismatch must choose B");
      assert.equal(verdict.failedField, "qualificationManifestDigest");
    }
  });

  test("held-out annotations conformance row: calibration rejects a leaked held-out id", () => {
    // A held-out label-bearing item must never enter the calibration fit. The
    // fit is REQUIRED to fail loudly (ENC_QUALIFICATION_HELD_OUT_IN_FIT) rather
    // than silently learning from review labels.
    const leaked = [...calExamples(), { itemId: "HELD-OUT-0001", head: "semantic" as EncoderHeadName, score: 0.99, label: 1 as const, repository: "repoZ", session: "s9" }];
    const fit = fitCalibration(leaked, { heldOutIds: ["HELD-OUT-0001"] });
    assert.equal(fit.ok, false);
    if (!fit.ok) assert.equal(fit.code, ENC_QUALIFICATION_FAIL.HELD_OUT_IN_FIT);
  });
});

// ---------------------------------------------------------------------------
// Suite 3 — split assignment invariants (grouped repo/session)
// ---------------------------------------------------------------------------
describe("split assignment invariance", () => {
  /** Deterministic split assignment: each repo/session group is assigned WHOLE
   *  to exactly one split (never split across boundaries). Seeded hashing on the
   *  stable group string. */
  function assignSplits(groups: { repository: string; session: string }[], seed: number): Record<string, "train" | "calibration" | "test"> {
    const out: Record<string, "train" | "calibration" | "test"> = {};
    for (const g of groups) {
      const key = `${g.repository}::${g.session}`;
      let state = (seed >>> 0) ^ 0x9e3779b9;
      for (const ch of key) state = (state * 1664525 + (ch.charCodeAt(0) + 1)) >>> 0;
      out[key] = (["train", "calibration", "test"] as const)[state % 3];
    }
    return out;
  }

  test("no repository+session group crosses a split boundary", () => {
    const groups = [
      { repository: "r1", session: "s1" },
      { repository: "r1", session: "s2" },
      { repository: "r2", session: "s1" },
      { repository: "r2", session: "s2" },
      { repository: "r3", session: "s1" },
    ];
    const assign = assignSplits(groups, 1729);
    // Every group is assigned exactly one split; a group key appears once.
    for (const g of groups) {
      const key = `${g.repository}::${g.session}`;
      assert.ok(assign[key] !== undefined, `${key} assigned`);
    }
    assert.equal(Object.keys(assign).length, groups.length, "no group duplicated");
    // The calibration split digest is stable regardless of initialization order.
    const ordered = calibrationSplitDigest(groups);
    const shuffled = calibrationSplitDigest([...groups].reverse());
    assert.equal(ordered, shuffled, "split digest invariant to row order");
  });

  test("selection is invariant to row order (calibration fit digest + thresholds stable)", () => {
    const ex = calExamples();
    const a = fitCalibration([...ex]);
    const b = fitCalibration([...ex].reverse());
    assert.equal(a.ok && b.ok, true);
    if (a.ok && b.ok) {
      assert.equal(a.calibration.calibrationSplitDigest, b.calibration.calibrationSplitDigest);
      for (const h of a.calibration.headOrder) {
        assert.equal(a.calibration.temperatures[h], b.calibration.temperatures[h]);
        assert.equal(a.calibration.thresholds[h], b.calibration.thresholds[h]);
      }
    }
  });
});

// ---------------------------------------------------------------------------
// Suite 4 — named assertions
// ---------------------------------------------------------------------------
describe("VC2C named assertions", () => {
  test("ENC-CAL-001: calibration fit excludes held-out fixture IDs from fit inputs", () => {
    const fx = fixture("ENC-CAL-001");
    assert.equal(fx.expected.ok, true);
    // Fitting the calibration split alone succeeds (no held-out leak).
    const fit = fitCalibration(calExamples());
    assert.equal(fit.ok, true);
    if (fit.ok) {
      assert.equal(fit.calibration.fittedOnCalibrationOnly, true);
      // Every head's temperature/threshold came from calibration-only examples.
      for (const h of fit.calibration.headOrder) {
        assert.ok(fit.calibration.thresholds[h] >= 0, `${h} threshold finite`);
      }
    }
    // A held-out duplicate placed in the fit is rejected (prohibition).
    const leaked = { ...calExamples()[0]!, itemId: "TEST-HELD-OUT-1" };
    const bad = fitCalibration([...calExamples(), leaked], { heldOutIds: ["TEST-HELD-OUT-1"] });
    assert.equal(bad.ok, false);
  });

  test("ENC-ATOMIC-002: one failed causal head demotes the entire A (no partial A)", () => {
    const fx = fixture("ENC-ATOMIC-002");
    assert.equal(fx.expected.ok, false);
    assert.equal(fx.expected.code, ENC_QUALIFICATION_FAIL.THRESHOLD_FAILED);
    const verdict = selectQualifiedEncoder(cleanCandidate(validCalibration(), oneFailedCausalHead()));
    assert.equal(verdict.ok, false);
    if (!verdict.ok) {
      assert.equal(verdict.code, ENC_QUALIFICATION_FAIL.THRESHOLD_FAILED);
      assert.equal(verdict.mode, "B", "atomic: no partial A");
    }
  });

  test("ENC-PACK-003: clean package listing contains the manifest + ONNX under 35 MiB", async () => {
    const fx = fixture("ENC-PACK-003");
    assert.equal(fx.expected.ok, true);
    const budget = fx.expected.budgetBytes ?? 35 * 1024 * 1024;
    const execFileP = promisify(execFile);
    const { stdout } = await execFileP("npm", ["pack", "--dry-run", "--json"], {
      cwd: REPO_ROOT,
      timeout: 120_000,
    });
    // `npm pack --json` returns an object keyed by package name with a `files`
    // array of {path,size,...} entries.
    const parsed = JSON.parse(stdout) as Record<string, { files?: { path: string; size: number }[] }>;
    const pack = Object.values(parsed)[0] ?? {};
    const files = pack.files ?? [];
    const total = files.reduce((acc, e) => acc + (Number(e.size) || 0), 0);
    assert.ok(total <= budget, `package listing ${total} bytes exceeds ${budget}`);
    assert.ok(
      files.some((e) => e.path.includes("assets/vector-cortex/encoder-v1/manifest.json")),
      "qualified encoder manifest listed in package",
    );
    assert.ok(
      files.some((e) => e.path.includes("assets/vector-cortex/encoder-v1/model.onnx")),
      "encoder ONNX listed in package",
    );
  });
});

// ---------------------------------------------------------------------------
// Suite 5 — unique failure injection + forced triad + fallback
// ---------------------------------------------------------------------------
describe("unique failure injection + forced triad", () => {
  test("corrupt qualification manifest after calibration, before selection -> ENC_QUALIFICATION_DIGEST_MISMATCH and choose B", () => {
    withFlagsOn(() => {
      const emitted: string[] = [];
      const reporter = createEncoderQualificationReporter((e) => emitted.push(e));
      const cal = validCalibration();
      const sealed = qualificationManifestDigest(cal);
      // Corruption: the on-disk calibration changes after calibration was sealed.
      const corrupt: CalibrationV1 = { ...cal, seed: cal.seed + 1 };
      const verdict = selectQualifiedEncoder(
        { ...cleanCandidate(cal, fullMetrics()), calibration: corrupt, expectedQualificationManifestDigest: sealed },
        { reporter },
      );
      assert.equal(verdict.ok, false);
      if (!verdict.ok) {
        assert.equal(verdict.code, ENC_QUALIFICATION_FAIL.DIGEST_MISMATCH);
        assert.equal(verdict.mode, "B", "chooses B on digest mismatch");
      }
      assert.ok(emitted.includes("vector_cortex_encoder_qualification_demoted"), "demoted event fired");
      // The fallback for the digest-mismatch code selects independently
      // initialized trigram B.
      const fb = selectQualificationFallback(ENC_QUALIFICATION_FAIL.DIGEST_MISMATCH, [1, 2, 3]);
      assert.equal(fb.mode, "B");
      assert.equal(fb.width, ENCODER_TRIGRAM_WIDTH);
    });
  });

  test("forced triad A / B / C through calibration + qualification fallback", () => {
    withFlagsOn(() => {
      // A = fully qualified learned asset: clean metrics pass -> QualifiedEncoderV1.
      const qualify = selectQualifiedEncoder(cleanCandidate(validCalibration(), fullMetrics()));
      assert.equal(qualify.ok, true);
      if (qualify.ok) assert.equal(qualify.qualified.mode, "A");

      // B = trigram forced by one failed threshold (causal head).
      const demote = selectQualifiedEncoder(cleanCandidate(validCalibration(), oneFailedCausalHead()));
      assert.equal(demote.ok, false);
      const fbB = selectQualificationFallback(ENC_QUALIFICATION_FAIL.THRESHOLD_FAILED, [1, 2, 3]);
      assert.equal(fbB.ok, true);
      assert.equal(fbB.mode, "B", "one failed threshold forces trigram B");
      assert.equal(fbB.vector.length, ENCODER_TRIGRAM_WIDTH);
      assert.equal(fbB.limitation, null);

      // C = lexical/exact forced by absent A AND an injected B error.
      const fbC = selectQualificationFallback(ENC_QUALIFICATION_FAIL.THRESHOLD_FAILED, [1, 2, 3], { injectBError: true });
      assert.equal(fbC.ok, true);
      assert.equal(fbC.mode, "C", "injected B error forces lexical C");
      assert.equal(fbC.vector.length, ENCODER_LEXICAL_WIDTH);
      assert.equal(fbC.limitation, ENCODER_LEXICAL_LIMITATION);

      // C reports its loss of old semantic context (continuity, not completeness).
      const lx = embedLexical(["vc2c", "forced", "triad"]);
      assert.equal(lx.length, ENCODER_LEXICAL_WIDTH);
      // A/B/C use disjoint widths (384/128/128/64/32, 512, 256).
      const aWidths = Object.values({ semantic: 384, dependency: 128, contradiction: 128, cacheStability: 64, payloadRouting: 32 });
      for (const w of [...aWidths, ENCODER_LEXICAL_WIDTH]) assert.notEqual(w, ENCODER_TRIGRAM_WIDTH);
    });
  });

  test("every MODEL_ASSET + per-head EVALUATION threshold is enforced at selection", () => {
    withFlagsOn(() => {
      // Asset failures demote A (atomic).
      const overTokens = selectQualifiedEncoder({
        ...cleanCandidate(validCalibration(), fullMetrics()),
        asset: { maxTokens: 600, latencyP95Ms: 20, rssDeltaMib: 40 },
      });
      assert.equal(overTokens.ok, false);
      if (!overTokens.ok) assert.equal(overTokens.failedField, "asset.maxTokens");

      const overLatency = selectQualifiedEncoder({
        ...cleanCandidate(validCalibration(), fullMetrics()),
        asset: { maxTokens: 512, latencyP95Ms: 200, rssDeltaMib: 40 },
      });
      assert.equal(overLatency.ok, false);
      if (!overLatency.ok) assert.equal(overLatency.failedField, "asset.latencyP95Ms");

      const overRss = selectQualifiedEncoder({
        ...cleanCandidate(validCalibration(), fullMetrics()),
        asset: { maxTokens: 512, latencyP95Ms: 20, rssDeltaMib: 900 },
      });
      assert.equal(overRss.ok, false);
      if (!overRss.ok) assert.equal(overRss.failedField, "asset.rssDeltaMib");

      // Per-head semantic failure demotes A.
      const v = selectQualifiedEncoder(cleanCandidate(validCalibration(), semanticFail()));
      assert.equal(v.ok, false);
      if (!v.ok) assert.equal(v.failedField, "head.semantic");
    });
  });
});

// ---------------------------------------------------------------------------
// Suite 6 — flag-off parity + emit seam
// ---------------------------------------------------------------------------
describe("VC2C flag-off parity + emit", () => {
  test("flag OFF yields ZERO VC2C emissions (byte-identical predecessor)", () => {
    const emitted: string[] = [];
    const saved = process.env.MEGACOMPACT_VC2C;
    process.env.MEGACOMPACT_VC2C = "0";
    try {
      const reporter = createEncoderQualificationReporter((e) => emitted.push(e));
      reporter.qualificationPassed({ mode: "A" });
      reporter.qualificationDemoted({ mode: "B", reason: "x" });
    } finally {
      if (saved === undefined) delete process.env.MEGACOMPACT_VC2C;
      else process.env.MEGACOMPACT_VC2C = saved;
    }
    assert.deepEqual(emitted, [], "flag OFF => no emissions");
  });

  test("flag ON: qualification passed/demoted emit their named events", () => {
    const emitted: string[] = [];
    const saved = process.env.MEGACOMPACT_VC2C;
    process.env.MEGACOMPACT_VC2C = "1";
    try {
      const reporter = createEncoderQualificationReporter((e) => emitted.push(e));
      const ok = selectQualifiedEncoder(cleanCandidate(validCalibration(), fullMetrics()), { reporter });
      assert.equal(ok.ok, true);
      const bad = selectQualifiedEncoder(cleanCandidate(validCalibration(), oneFailedCausalHead()), { reporter });
      assert.equal(bad.ok, false);
    } finally {
      if (saved === undefined) delete process.env.MEGACOMPACT_VC2C;
      else process.env.MEGACOMPACT_VC2C = saved;
    }
    assert.ok(emitted.includes("vector_cortex_encoder_qualification_passed"));
    assert.ok(emitted.includes("vector_cortex_encoder_qualification_demoted"));
  });

  test("VC2C flag is defined, default ON, and =0 disables", () => {
    const saved = process.env.MEGACOMPACT_VC2C;
    delete process.env.MEGACOMPACT_VC2C;
    try {
      assert.equal(VC2C_ENABLED(), true, "default ON");
    } finally {
      if (saved !== undefined) process.env.MEGACOMPACT_VC2C = saved;
    }
    process.env.MEGACOMPACT_VC2C = "0";
    assert.equal(VC2C_ENABLED(), false, "=0 disables");
    process.env.MEGACOMPACT_VC2C = "1";
    assert.equal(VC2C_ENABLED(), true, "pinned ON");
  });
});

describe("VC2C helper route digest", () => {
  test("qualificationManifestDigest is deterministic and stable", () => {
    const cal = validCalibration();
    assert.equal(qualificationManifestDigest(cal), qualificationManifestDigest(cal));
    assert.equal(qualificationManifestDigest(cal).length, 64);
  });
});
