export const meta = {
  name: "s20-s23-v050",
  description: "Parallel 3-agent-per-sprint: S20 memory-RAG + trigger, S21 recall+consolidate, S22 docs, S23 release for v0.5.0. Disjoint file ownership so 3 agents run concurrently per phase.",
  phases: [
    {title:"S20 memory apply+trigger (3 parallel)", detail:"applyMemoryOps + trigger + CHANGELOG"},
    {title:"S21 memory recall+consolidate (3 parallel)", detail:"recallMemories + merge-recall + consolidate"},
    {title:"S22 docs (3 parallel)", detail:"README + maps + guardrails audit"},
    {title:"S23 release (sequential)", detail:"benchmarks then version+tag+publish"},
  ],
};

const CO = "Co-Authored-By: Claude Fable 5 <noreply@anthropic.com>";
const GRD = "\nGUARDRAILS (every agent MUST obey):\n- Work ONLY on the files listed for your task. Do NOT edit files owned by other agents in the same phase.\n- PREVENT-PI-004 (critical): ZERO network calls at runtime. No fetch/http.request/https to non-loopback. Only allowed loopback is localhost Ollama.\n- PREVENT-PI-001/002/003: recall injects via before_agent_start (never role: 'system').\n- PREVENT-DIST-001: ship via npm publish only — never a .tgz.\n- Commit message ends with: "+CO+"\n- GATE before commit: npm run build && node scripts/run-tests.mjs && npm run lint && python3 scripts/regression_check.py --all (0 failures).\n- Gate failure you cannot fix in scope = STOP, report, no force-commit.\n";

phase("Phase 1: S20.3 — applyMemoryOps + trigger + CHANGELOG (3 parallel)");

await parallel([
  async () => { await agent("S20.3a applyMemoryOps", {label:"S20.3a-applyOps",prompt:"Implement applyMemoryOps for pi-mega-compact (S20.3). Branch feat/continuity-crossrepo. S20.1 (schema columns) + S20.2 (reviewConversation) are committed.\n\nCREATE src/memoryOps.ts (do NOT edit src/memory.ts):\n  import type { MemoryOp } from './memory.js';\n  export async function applyMemoryOps(ops: MemoryOp[], stateDir: string): Promise<void>\n    - ADD -> use the existing addMemory helper in src/store/sqlite.ts. Map: addMemory({ kind: op.memory.category, content: op.memory.content, category: op.memory.category, target: op.memory.target, sourceTurn: op.memory.sourceTurn }).\n    - REPLACE -> UPDATE memories SET content=?, category=?, source_turn=?, last_referenced=? WHERE content=? (parameterized — read src/store/sqlite.ts for the correct DB accessor).\n    - REMOVE -> DELETE FROM memories WHERE content=?\n    - Parameterized SQL only. Open the store via the same openStore(stateDir) pattern src/store/sqlite.ts uses.\n\nTEST src/memoryOps.test.ts (node:test, assert/strict): seed a memory, apply REPLACE op, assert content updated; apply ADD, assert present; apply REMOVE, assert gone. Use os.tmpdir() for a temp store.\n\nCHANGELOG: do NOT touch (another agent owns it).\n"+GRD+"\nSTEPS: npm run build; node scripts/run-tests.mjs; npm run lint; python3 scripts/regression_check.py --all.\nCommit: git add src/memoryOps.ts src/memoryOps.test.ts && git commit -m 'feat(memory): applyMemoryOps add/replace/remove (S20)' with "+CO+". Return the commit hash."}); },
  async () => { await agent("S20.3b turn_end trigger + config", {label:"S20.3b-trigger",prompt:"Wire the memory auto-review trigger (S20.3). Branch feat/continuity-crossrepo. S20.2 reviewConversation + S20.3a applyMemoryOps (src/memoryOps.ts) are committed or being committed in parallel.\n\nFILES YOU EDIT (disjoint from other agents): extensions/mega-events.ts, extensions/mega-config.ts. Do NOT edit src/memory.ts, src/memoryOps.ts, or CHANGELOG.md.\n\nSTEP 1 — extensions/mega-events.ts turn_end handler: after the existing snapshot/event logic, add a debounced auto-review block:\n  if (config.memoryAutoReview && runtime.currentTurn > 0 && runtime.currentTurn % config.memoryReviewInterval === 0) {\n    try {\n      const { reviewConversation } = await import('../src/memory.js');\n      const { applyMemoryOps } = await import('../src/memoryOps.js');\n      const entries = ctx.sessionManager.getEntries();\n      const view = runtime.engineView(entries.flatMap((e) => (e.message ? [e.message] : [])));\n      const ops = reviewConversation(view, []);\n      if (ops.length) await applyMemoryOps(ops, runtime.currentStateDir);\n    } catch { /* non-fatal */ }\n  }\n  Read the existing turn_end handler FIRST to match its style. Do NOT duplicate existing snapshot/event calls.\n\nSTEP 2 — extensions/mega-config.ts: add (match the existing envBool/envInt helper names):\n  memoryAutoReview: envBool('MEGACOMPACT_MEMORY_AUTO_REVIEW', true),\n  memoryReviewInterval: envInt('MEGACOMPACT_MEMORY_REVIEW_INTERVAL', 10),\n\n"+GRD+"\nSTEPS: npm run build; node scripts/run-tests.mjs; npm run lint; python3 scripts/regression_check.py --all.\nCommit: git add extensions/mega-events.ts extensions/mega-config.ts && git commit -m 'feat(memory): auto-review trigger every N turns (S20)' with "+CO+". Return the commit hash."}); },
  async () => { await agent("S20.3c CHANGELOG S20", {label:"S20.3c-changelog",prompt:"Write the S20 CHANGELOG section ONLY. Branch feat/continuity-crossrepo. FILE: CHANGELOG.md ONLY — do NOT edit any source/test file.\n\nADD at the TOP (before the existing S19 header):\n## v0.5.0-unreleased — Sprint S20 (memory auto-review)\n\n### Added\n- reviewConversation() (src/memory.ts) — extractive, hallucination-guarded review of recent user requests. Detects decision statements (DECISION_PATTERNS), emits add/replace/remove MemoryOp, grounds every op in actual message text.\n- applyMemoryOps() (src/memoryOps.ts) — applies add/replace/remove ops to the memories table (parameterized SQL, idempotent).\n- Auto-review trigger — extensions/mega-events.ts turn_end fires reviewConversation + applyMemoryOps every MEGACOMPACT_MEMORY_REVIEW_INTERVAL turns (default 10) when MEGACOMPACT_MEMORY_AUTO_REVIEW is on (default true). Best-effort, non-fatal.\n- memories table gains category/target/last_referenced/source_turn columns (S20.1, additive + idempotent migration).\n\n### Tests\n- src/memory.test.ts (3): add, replace, none-on-smalltalk. src/memoryOps.test.ts: add/replace/remove ops.\n\nRead CHANGELOG.md first to match the format and insert in the right place.\n"+GRD+"\nSTEPS: npm run build. git add CHANGELOG.md && git commit -m 'docs: CHANGELOG S20 (memory auto-review)' with "+CO+". Return commit hash."}); },
]);

phase("Phase 2: S21 — recallMemories + merge-recall + consolidate (3 parallel)");

await parallel([
  async () => { await agent("S21.1a recallMemories", {label:"S21.1a-recallMemories",prompt:"Implement recallMemories for pi-mega-compact (S21). Branch feat/continuity-crossrepo. S20 is committed.\n\nCREATE src/memoryRecall.ts (do NOT edit src/memory.ts):\n  export function recallMemories(query: string, stateDir: string, k = 5): { content: string; category: string; sourceTurn: number }[]\n    - Read this repo's memories from sqlite using the existing listMemories helper in src/store/sqlite.ts (grep for listMemories, addMemory, openStore). Parameterized SQL only.\n    - Rank by relevance to query: embed query + each memory via the embedder (grep src/embedder.ts for the default embedder export), use cosineSimilarity from ./vectorStore.js or compute a simple trigram cosine locally.\n    - Boost recently-referenced memories (last_referenced) by a small factor.\n    - Return top-k by score.\n  - LOCAL only (PREVENT-PI-004). Read src/store/sqlite.ts and src/embedder.ts first to use real exports.\n\nTEST src/memoryRecall.test.ts: seed two memories (sqlite vs cats) in a temp store, call recallMemories('sqlite store', stateDir, 5), assert the sqlite memory is returned (top-1 or present). Use os.tmpdir().\n\nCHANGELOG: do NOT touch.\n"+GRD+"\nSTEPS: npm run build; node scripts/run-tests.mjs; npm run lint; python3 scripts/regression_check.py --all.\nCommit: git add src/memoryRecall.ts src/memoryRecall.test.ts && git commit -m 'feat(memory): recallMemories relevance scan (S21)' with "+CO+". Return commit hash."}); },
  async () => { await agent("S21.1b merge memories into recall path", {label:"S21.1b-mergeRecall",prompt:"Merge memories into the recall path (S21). Branch feat/continuity-crossrepo. S21.1a recallMemories (src/memoryRecall.ts) is committed or being committed in parallel.\n\nFILES YOU EDIT: src/recall.ts and src/recall.test.ts. Do NOT edit src/memory.ts or src/memoryRecall.ts.\n\nTASK: in recallAndInline (and recallAndInlineAsync if it exists), after checkpoint hits are assembled, call recallMemories(query, stateDir, k) and merge the returned memories as labeled entries (marker 'memory'), respecting recallMaxTokens cap + windowDedupe. Bump last_referenced (UPDATE memories SET last_referenced = ? WHERE id = ?) on injected memory rows.\n\nMatch the EXISTING injection shape — this repo injects recall via before_agent_start systemPrompt prepend, NOT via role: 'system' (PREVENT-PI-003). Read recall.ts fully first.\n\nTEST src/recall.test.ts: extend or add a test — seed a matching memory, run recall, assert a 'memory'-labeled entry appears within the token cap.\n\nCHANGELOG: do NOT touch.\n"+GRD+"\nSTEPS: npm run build; node scripts/run-tests.mjs; npm run lint; python3 scripts/regression_check.py --all.\nCommit: git add src/recall.ts src/recall.test.ts && git commit -m 'feat(memory): include memories in recall (capped, labeled) (S21)' with "+CO+". Return commit hash."}); },
  async () => { await agent("S21.2 consolidate memories", {label:"S21.2-consolidate",prompt:"Implement memory consolidation (S21.2). Branch feat/continuity-crossrepo. S21.1 committed.\n\nCREATE src/memoryConsolidate.ts (do NOT edit src/memory.ts):\n  export function consolidateMemories(stateDir: string): void\n    - Load all memories for the repo. Find pairs with cosine similarity > 0.95 (use cosineSimilarity from ./vectorStore.js — grep for it). For each near-dup pair, merge: keep the higher-category / more-recent, append the other's content to it, and DELETE the duplicate row.\n    - Parameterized SQL via src/store/sqlite.ts.\n\nEDIT extensions/mega-pipeline.ts: in doCompact, after compaction completes, call consolidateMemories(runtime.currentStateDir) inside try/catch (non-fatal). Read doCompact FIRST to match style.\n\nTEST src/memoryConsolidate.test.ts: seed two near-duplicates ('we use node:sqlite' / 'our store is node:sqlite'), run consolidateMemories, assert only one remains. Use os.tmpdir().\n\nCHANGELOG: do NOT touch.\n"+GRD+"\nSTEPS: npm run build; node scripts/run-tests.mjs; npm run lint; python3 scripts/regression_check.py --all.\nCommit: git add src/memoryConsolidate.ts src/memoryConsolidate.test.ts extensions/mega-pipeline.ts && git commit -m 'feat(memory): auto-consolidate near-duplicate memories (S21)' with "+CO+". Return commit hash."}); },
]);

phase("Phase 3: S22 docs — README + maps + guardrails (3 parallel)");

await parallel([
  async () => { await agent("S22.1 README", {label:"S22.1-readme",prompt:"Update README for pi-mega-compact v0.5.0 (S22). Branch feat/continuity-crossrepo. FILE: README.md ONLY.\n\nAfter 'Install from npm', add:\n### Storage backend (v0.5.0+)\npi-mega-compact uses a dual local backend — zero network, no native build step:\n- node:sqlite (DatabaseSync, Node >=22.13 built-in) — synchronous source of truth for checkpoints, session state, and the dedup index. No dependency, no install script.\n- PGlite + @electric-sql/pglite-pgvector (WASM Postgres + HNSW vector_cosine_ops) — optional, best-effort async vector index for cross-repo recall. Sync store stays authoritative; degrades to sync per-session scan on failure.\nKill-switch: MEGACOMPACT_PGLITE_DISABLED=1 fully disables PGlite. Requires Node >=22.13.\n\n### Cross-repo recall (v0.5.0+)\nOn resume, recall augments from other repos' checkpoints when this repo's store is thin; /mega-recall --cross-repo searches all repos via the HNSW index. Cross-repo hits use a stricter cosine floor (MEGACOMPACT_CROSSREPO_COSINE, default 0.90) labeled with source repo. A machine-wide injected-set prevents re-injecting the same foreign checkpoint.\n\n### Memory (v0.5.0+)\npi-mega-compact auto-reviews the conversation every 10 turns and writes durable decision/fact/preference memories to SQLite (local, hallucination-guarded). Relevant memories are injected as RAG context on recall (capped, deduped). Manual: /mega-memory save|list|forget.\n\nMatch README tone (read it first). No invented features.\n"+GRD+"\nSTEPS: npm run build. git add README.md && git commit -m 'docs: dual-backend + cross-repo + memory README (S22)' with "+CO+". Return commit hash."}); },
  async () => { await agent("S22.2 maps", {label:"S22.2-maps",prompt:"Update docs maps for pi-mega-compact (S22.2). Branch feat/continuity-crossrepo. FILES: docs/INDEX_MAP.md and docs/HEADER_MAP.md ONLY.\n\nUpdate both to reference S16-S21 features:\n  - docs/superpowers/CONTINUITY-BRANCH-ROADMAP.md, docs/superpowers/plans/2026-07-15-compaction-continuity-cross-repo-memory.md, docs/superpowers/specs/2026-07-15-compaction-continuity-cross-repo-memory-design.md\n  - features: compaction continuity (live trim + native durable), cross-repo recall (PGlite HNSW), machine-wide injected-set, multi-repo dashboard (/api/index), memory-RAG auto-review + recall + consolidate\n  - new modules: src/memory.ts, src/memoryOps.ts, src/memoryRecall.ts, src/memoryConsolidate.ts, src/store/vectorIndex.ts, extensions/dashboard-server.ts\nRead both files first; preserve format; append/update entries.\n"+GRD+"\nSTEPS: npm run build. git add docs/INDEX_MAP.md docs/HEADER_MAP.md && git commit -m 'docs: maps reference S16-S21 features (S22)' with "+CO+". Return commit hash."}); },
  async () => { await agent("S22.3 guardrails", {label:"S22.3-audit",prompt:"Final guardrails audit (S22.3). Branch feat/continuity-crossrepo. Run the FULL GATE and leave repo green. Do NOT modify feature code unless it breaks a guardrail.\n\nRUN: npm run build && node scripts/run-tests.mjs && npm run lint && python3 scripts/regression_check.py --all &&\ngrep -rn 'fetch|http.request|https.' src extensions | grep -v node_modules | grep -v 'loopback|127.0.0.1|localhost|// guardrails-allow'\nZERO unexpected network calls (PREVENT-PI-004). If flagged, verify loopback-only or add // guardrails-allow comment.\n\n"+GRD+"\nIf you fixed something: git add -A && git commit -m 'chore: S22 guardrails audit green' with "+CO+". If green: return 'GREEN — no commit needed'."}); },
]);

phase("Phase 4: S23 release — benchmarks then version+tag+publish");

await agent("S23.1 benchmarks + DR drill", {label:"S23.1-bench",prompt:"Add/release benchmarks for pi-mega-compact (S23.1). Branch feat/continuity-crossrepo. S16-S22 committed.\n\n- Extend scripts/dedup-benchmark.mjs or add scripts/crossrepo-benchmark.mjs measuring: cross-repo recall latency + quality (HNSW vs sync scan), compaction-continuity (model-context-drops > 5:1), memory-RAG recall hit rate (top-1 of seeded memory).\n- Run bash scripts/dedup-restore-drill.sh. Add a global-index DR check (delete global-index.db, restart, assert rebuild). Create/extend script minimally if missing.\n- LOCAL only (PREVENT-PI-004).\n\n"+GRD+"\nSTEPS: npm run build; run benches + DR drill. git add scripts/ && git commit -m 'bench: cross-repo + continuity + memory benchmarks (S23)' with "+CO+". Return commit hash."});

await agent("S23.2 version bump + tag + publish", {label:"S23.2-publish",prompt:"Release pi-mega-compact v0.5.0 (S23.2). Branch feat/continuity-crossrepo. S23.1 committed. User AUTHORIZED publish.\n\n1. package.json: version to '0.5.0'.\n2. CHANGELOG.md: consolidate top 'v0.5.0-unreleased' headers (S16-S22) into '## v0.5.0 (2026-07-15)' release section. Keep detail, mark released.\n3. FULL gate GREEN: npm run build && node scripts/run-tests.mjs && npm run lint && python3 scripts/regression_check.py --all\n4. git add package.json CHANGELOG.md && git commit -m '0.5.0' with "+CO+"\n5. git tag v0.5.0 && git push --follow-tags && npm publish   (npm ONLY, never .tgz — PREVENT-DIST-001). If npm publish fails auth/2FA, stop and report.\n\n"+GRD+"\nReturn: final commit hash, tag, and npm publish result."});
